language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script:
  - vendor/bin/phpcs --report-full --standard=PSR2 src
  - vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode
